# Generated by Django 5.1.6 on 2025-02-18 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cars', '0004_alter_auccars_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery', models.PositiveIntegerField(help_text='в ваоюте', verbose_name='доставка в РФ')),
                ('commission_broker', models.PositiveIntegerField(help_text='в рублях', verbose_name='Брокер')),
                ('commission', models.PositiveIntegerField(help_text='в рублях', verbose_name='Комиссия')),
                ('japan_sanction_delivery', models.PositiveIntegerField(blank=True, help_text='в валюте страны экспортера', null=True, verbose_name='Доставка санкционного авто')),
                ('japan_sanction_percent', models.PositiveIntegerField(blank=True, help_text='в процентах', null=True, verbose_name='Процент комиссии санкционных авто')),
                ('japan_insurance', models.PositiveIntegerField(blank=True, help_text='в валюте страны экспортера', null=True, verbose_name='Страховка')),
                ('table', models.CharField(max_length=50, verbose_name='Таблица в API')),
                ('country', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='cars.country', verbose_name='Страна экспортер')),
            ],
            options={
                'verbose_name': 'комиссия',
                'verbose_name_plural': 'комиссии',
                'ordering': ('country',),
            },
        ),
    ]
