# Generated by Django 5.1.6 on 2025-02-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('KRW', 'KRW'), ('JPY_crypto', 'JPY_crypto'), ('CNY_crypto', 'CNY_crypto'), ('KRW_crypto', 'KRW_crypto')], max_length=200, verbose_name='Название')),
                ('exchange_rate', models.FloatField(default=0.0, verbose_name='Курс')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
