# Generated by Django 5.1.6 on 2025-02-17 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auccars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auccars',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в РФ'),
        ),
    ]
