# Generated by Django 5.1.6 on 2025-02-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_alter_auccars_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auccars',
            name='toll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пошлина'),
        ),
    ]
