# Generated by Django 5.1.6 on 2025-02-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auccars_toll'),
    ]

    operations = [
        migrations.AddField(
            model_name='auccarschina',
            name='toll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пошлина'),
        ),
        migrations.AddField(
            model_name='auccarseurope',
            name='toll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пошлина'),
        ),
        migrations.AddField(
            model_name='auccarsjapan',
            name='toll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пошлина'),
        ),
        migrations.AddField(
            model_name='auccarskorea',
            name='toll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пошлина'),
        ),
        migrations.AddField(
            model_name='auccarsusa',
            name='toll',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пошлина'),
        ),
    ]
