# Generated by Django 5.1.6 on 2025-02-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auccarschina_toll_auccarseurope_toll_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auccarschina',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в РФ'),
        ),
        migrations.AlterField(
            model_name='auccarseurope',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в РФ'),
        ),
        migrations.AlterField(
            model_name='auccarsjapan',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в РФ'),
        ),
        migrations.AlterField(
            model_name='auccarskorea',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена в РФ'),
        ),
    ]
