# Generated by Django 5.1.6 on 2025-02-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_alter_auccarschina_price_alter_auccarseurope_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AucCarsUSA',
            new_name='AucCarsRest',
        ),
        migrations.AlterModelOptions(
            name='auccarsrest',
            options={'verbose_name': 'Автомобили (другое)', 'verbose_name_plural': 'Автомобили (другое)'},
        ),
        migrations.DeleteModel(
            name='AucCars',
        ),
    ]
