# Generated by Django 5.1.6 on 2025-02-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_rename_auccarsusa_auccarsrest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auccarseurope',
            name='brand_country',
        ),
        migrations.RemoveField(
            model_name='auccarseurope',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='auccarsjapan',
            name='brand_country',
        ),
        migrations.RemoveField(
            model_name='auccarsjapan',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='auccarskorea',
            name='brand_country',
        ),
        migrations.RemoveField(
            model_name='auccarskorea',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='auccarsrest',
            name='brand_country',
        ),
        migrations.RemoveField(
            model_name='auccarsrest',
            name='photos',
        ),
        migrations.CreateModel(
            name='AucCars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auc_table', models.CharField(max_length=50, verbose_name='Таблица во внешнем апи')),
                ('lot', models.CharField(max_length=50, verbose_name='Номер лота')),
                ('auc_name', models.CharField(max_length=50, verbose_name='Название аукциона')),
                ('api_id', models.CharField(max_length=50, unique=True, verbose_name='ID автомобиля')),
                ('brand', models.CharField(max_length=50, verbose_name='Бренд')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('mileage', models.IntegerField(verbose_name='Пробег')),
                ('toll', models.IntegerField(blank=True, null=True, verbose_name='Пошлина')),
                ('kuzov', models.CharField(max_length=50, verbose_name='Тип кузова')),
                ('transmission', models.CharField(max_length=50, verbose_name='Тип КПП')),
                ('engine_volume', models.CharField(max_length=50, verbose_name='Объем двигателя')),
                ('drive', models.CharField(max_length=50, verbose_name='Тип привода')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('rate', models.CharField(max_length=5, verbose_name='Рейтинг')),
                ('finish', models.CharField(max_length=50, verbose_name='Цена в валюте экспортера')),
                ('power_volume', models.CharField(blank=True, max_length=30, null=True, verbose_name='Мощность двигателя')),
                ('parsing_date', models.DateField(auto_now=True, verbose_name='Дата парсинга')),
                ('rubber', models.CharField(blank=True, choices=[('Левый руль', 'Левый руль'), ('Правый руль', 'Правый руль')], default='Левый руль', max_length=30, null=True, verbose_name='Руль')),
                ('engine', models.CharField(blank=True, choices=[('Электро', 'Электро'), ('Гибрид', 'Гибрид'), ('Дизель', 'Дизель'), ('Бензин', 'Бензин')], default='Бензин', max_length=30, null=True, verbose_name='Тип двигателя')),
                ('is_active', models.BooleanField()),
                ('month', models.CharField(blank=True, max_length=20, null=True, verbose_name='Месяц')),
                ('grade', models.CharField(blank=True, max_length=200, null=True, verbose_name='Grade')),
                ('kpp', models.CharField(blank=True, max_length=100, null=True, verbose_name='КПП')),
                ('equip', models.CharField(blank=True, max_length=200, null=True, verbose_name='Equip')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Статус')),
                ('time', models.CharField(blank=True, max_length=10, null=True, verbose_name='Time')),
                ('brand_country', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.countrymodels', verbose_name='Страна производитель')),
                ('photos', models.ManyToManyField(to='cars.auccarsphoto', verbose_name='Фотографии автомобиля')),
            ],
            options={
                'verbose_name': 'Автомобили',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.DeleteModel(
            name='AucCarsChina',
        ),
        migrations.DeleteModel(
            name='AucCarsEurope',
        ),
        migrations.DeleteModel(
            name='AucCarsJapan',
        ),
        migrations.DeleteModel(
            name='AucCarsKorea',
        ),
        migrations.DeleteModel(
            name='AucCarsRest',
        ),
    ]
