# Generated by Django 5.1.6 on 2025-02-26 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_remove_auccarseurope_brand_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auccars',
            name='auc_table',
        ),
        migrations.RemoveField(
            model_name='auccars',
            name='rubber',
        ),
        migrations.RemoveField(
            model_name='auccars',
            name='time',
        ),
    ]
