# Generated by Django 5.1.6 on 2025-02-26 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_remove_auccars_auc_table_remove_auccars_rubber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auccars',
            old_name='kuzov',
            new_name='body_type',
        ),
        migrations.AddField(
            model_name='auccars',
            name='auction',
            field=models.CharField(default='encar', max_length=50, verbose_name='Аукцион'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auccars',
            name='body_brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кузов'),
        ),
    ]
