# Generated by Django 5.1.6 on 2025-02-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_rename_kuzov_auccars_body_type_auccars_auction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auccars',
            name='auc_name',
        ),
        migrations.RemoveField(
            model_name='auccars',
            name='status',
        ),
        migrations.AlterField(
            model_name='auccars',
            name='body_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип кузова'),
        ),
    ]
