# Generated by Django 5.1.6 on 2025-04-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_remove_auccars_auc_name_remove_auccars_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuBodyTypeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type_ru', models.CharField(max_length=250, verbose_name='Русифицированный тип кузова')),
                ('body_type', models.TextField(help_text='Через зяпятую', verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузовов',
            },
        ),
        migrations.CreateModel(
            name='RuBrandCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=250, verbose_name='марка')),
                ('ru_brand', models.CharField(max_length=250, verbose_name='перевод марки')),
            ],
            options={
                'verbose_name': 'Перевод марки',
                'verbose_name_plural': 'Переводы марок',
            },
        ),
        migrations.CreateModel(
            name='RuColorCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=250, verbose_name='марка')),
                ('ru_color', models.CharField(max_length=250, verbose_name='перевод марки')),
            ],
            options={
                'verbose_name': 'Перевод цвета',
                'verbose_name_plural': 'Переводы цветов',
            },
        ),
        migrations.CreateModel(
            name='RuDriveCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_ru', models.CharField(max_length=250, verbose_name='Русифицированный тип привода')),
                ('drive', models.TextField(help_text='Через зяпятую', verbose_name='Тип привода')),
            ],
            options={
                'verbose_name': 'Тип привода',
                'verbose_name_plural': 'Типы приводов',
            },
        ),
        migrations.CreateModel(
            name='RuEngineCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_ru', models.CharField(max_length=250, verbose_name='Русифицированный тип топлива')),
                ('engine', models.TextField(help_text='Через зяпятую', verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Типы топлива',
            },
        ),
        migrations.CreateModel(
            name='RuModelCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=250, verbose_name='марка')),
                ('ru_model', models.CharField(max_length=250, verbose_name='перевод марки')),
            ],
            options={
                'verbose_name': 'Перевод модели',
                'verbose_name_plural': 'Переводы моделей',
            },
        ),
        migrations.CreateModel(
            name='RuTransmissionCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transmission_ru', models.CharField(max_length=250, verbose_name='Русифицированный тип КПП')),
                ('transmission', models.TextField(help_text='Через зяпятую', verbose_name='Тип КПП')),
            ],
            options={
                'verbose_name': 'Тип КПП',
                'verbose_name_plural': 'Типы КПП',
            },
        ),
        migrations.RemoveField(
            model_name='auccars',
            name='kpp',
        ),
        migrations.AlterField(
            model_name='auccars',
            name='equip',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Детали комплектации'),
        ),
        migrations.AlterField(
            model_name='auccars',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='auccars',
            name='rate',
            field=models.CharField(max_length=50, verbose_name='Рейтинг'),
        ),
    ]
